//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP2.HR.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERINFO
    {
        public string USERID { get; set; }
        public string PASSWORD { get; set; }
        public System.DateTime DOB { get; set; }
        public string DEPARTMENT { get; set; }
        public string GENDER { get; set; }
    }
}
